const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require("docx");

const doc = new Document({
    sections: [
        {
            properties: {},
            children: [
                new Paragraph({
                    text: "Software Development Agreement: AI Voice Assistant",
                    heading: HeadingLevel.HEADING_1,
                }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Client: ", bold: true }),
                        new TextRun("Micro Technique IT"),
                    ],
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Developer: ", bold: true }),
                        new TextRun("[Your Name / Company Name]"),
                    ],
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Date: ", bold: true }),
                        new TextRun("July 2, 2026"),
                    ],
                }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "1. Scope of Work (Deliverables)",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    text: "The Developer agrees to build and deliver a single, custom AI Voice Assistant solution for the Client. The deliverables are strictly limited to the following:",
                }),
                new Paragraph({ text: "- AI Call Assistant: A custom Node.js backend integrating Twilio, Deepgram (Speech-to-Text & Text-to-Speech), and Groq (LLM) to handle inbound phone calls using a specific system prompt.", bullet: { level: 0 } }),
                new Paragraph({ text: "- Database (DB): A PostgreSQL database setup to automatically extract and store lead information (e.g., Name, Phone Number, City, State) generated from the AI phone calls.", bullet: { level: 0 } }),
                new Paragraph({ text: "- Dashboard: A web-based dashboard (React) connected to the database, allowing the Client to view their extracted leads and call transcripts.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "(Note: This is a single-use deployment for one business entity, not a multi-tenant SaaS platform).", italics: true }),
                    ],
                }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "2. Infrastructure & Third-Party APIs",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    text: "The Client (Micro Technique IT) is responsible for provisioning, managing, and paying for all third-party services and infrastructure required for the software to operate.",
                }),
                new Paragraph({ text: "- The Client will provide the Developer with valid API keys and/or active billing accounts for the following services: Twilio, Deepgram, Groq, and Cloud Hosting.", bullet: { level: 0 } }),
                new Paragraph({ text: "- The Developer is not responsible for any recurring costs, API usage fees, or overage charges generated by the software.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "3. Payment Terms",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    children: [
                        new TextRun("The total fixed project fee is "),
                        new TextRun({ text: "₹25,000 INR.", bold: true }),
                    ],
                }),
                new Paragraph({ text: "- Payment Schedule: 100% of the project fee (₹25,000 INR) is due in full on or before July 6, 2026.", bullet: { level: 0 } }),
                new Paragraph({ text: "- Cancellation: Once development has commenced or API integrations have been initiated, the project cannot be cancelled or reverted by the Client. The Client remains legally obligated to remit the full agreed-upon project fee of ₹25,000 INR regardless of any change in business direction.", bullet: { level: 0 } }),
                new Paragraph({ text: "- Upon receipt of the full payment, the final codebase will be handed over to the Client.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "4. Intellectual Property (Work for Hire)",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    text: "This project is designated as a 'Work made for hire.'",
                }),
                new Paragraph({ text: "- Upon receipt of the full ₹25,000 INR payment, the Developer will transfer 100% of the ownership and intellectual property rights of the custom-written source code to Micro Technique IT.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "5. Data Privacy & Legal Compliance",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    text: "The software involves the recording of telephone conversations and the extraction of personal user data (leads).",
                }),
                new Paragraph({ text: "- Legal Liability: Micro Technique IT assumes all legal responsibility for the operation of the software.", bullet: { level: 0 } }),
                new Paragraph({ text: "- Compliance: It is the sole responsibility of the Client to ensure compliance with all applicable local, state, and federal telecom regulations (including Two-Party Consent recording laws) and data privacy regulations. The Developer assumes no liability for the misuse of the software or failure to adhere to legal compliance by the Client.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({ text: "---" }),
                new Paragraph({ text: "" }),
                new Paragraph({ text: "Signatures:" }),
                new Paragraph({ text: "" }),
                new Paragraph({ text: "___________________________" }),
                new Paragraph({ children: [new TextRun({ text: "[Your Name] (Developer)", bold: true })] }),
                new Paragraph({ text: "Date: _______________" }),
                new Paragraph({ text: "" }),
                new Paragraph({ text: "___________________________" }),
                new Paragraph({ children: [new TextRun({ text: "Representative for Micro Technique IT", bold: true })] }),
                new Paragraph({ text: "Date: _______________" }),
            ],
        },
    ],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("Single_Use_Agreement.docx", buffer);
    console.log("Created Single_Use_Agreement.docx");
});
