const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require("docx");

const doc = new Document({
    sections: [
        {
            properties: {},
            children: [
                new Paragraph({
                    text: "Software Development Agreement: AI Voice SaaS Platform",
                    heading: HeadingLevel.HEADING_1,
                }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Client: ", bold: true }),
                        new TextRun("Micro Technique IT"),
                    ],
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Developer: ", bold: true }),
                        new TextRun("[Your Name / Company Name]"),
                    ],
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: "Date: ", bold: true }),
                        new TextRun("July 2, 2026"),
                    ],
                }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "1. Scope of Work (Deliverables)",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    text: "The Developer agrees to build and deliver a multi-tenant AI Voice Assistant Software-as-a-Service (SaaS) platform. The deliverables include:",
                }),
                new Paragraph({ text: "- Landing Page: A marketing website designed to showcase the platform's features, display pricing tiers, and facilitate user registration.", bullet: { level: 0 } }),
                new Paragraph({ text: "- SaaS Dashboard (Multi-Tenant): A secure web portal where the Client's customers can log in, configure their custom AI Voice Assistants, manage their Twilio phone numbers, and view extracted call leads and transcripts.", bullet: { level: 0 } }),
                new Paragraph({ text: "- Multi-Tenant AI Backend: The core Node.js server infrastructure capable of dynamically orchestrating Twilio, Deepgram (Speech-to-Text and Text-to-Speech), and Groq (LLM) APIs. The backend will route and handle simultaneous calls for multiple distinct clients using shared infrastructure.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "2. Infrastructure & Third-Party APIs",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    text: "The Client (Micro Technique IT) is responsible for provisioning, managing, and paying for all third-party services and infrastructure required for the platform to operate.",
                }),
                new Paragraph({ text: "- The Client will provide the Developer with valid API keys and/or active billing accounts for the following services: Twilio, Deepgram, Groq, and Cloud Hosting (e.g., AWS, Vercel, DigitalOcean).", bullet: { level: 0 } }),
                new Paragraph({ text: "- The Developer is not responsible for any recurring costs, API usage fees, or overage charges generated by the platform or its end-users.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "3. Payment Structure",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    text: "The total project fee will be paid by the Client to the Developer according to the following milestone schedule:",
                }),
                new Paragraph({ text: "- 20% Upfront: Due upon signing this agreement, prior to the commencement of development.", bullet: { level: 0 } }),
                new Paragraph({ text: "- 30% Upon Final Demo: Due upon the Developer presenting a fully functional, end-to-end demonstration of the platform (Landing Page, Dashboard, and AI Backend).", bullet: { level: 0 } }),
                new Paragraph({ text: "- 50% Upon Launch: Due upon final handover of the codebase and deployment of the platform to the Client's production infrastructure.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "4. Intellectual Property (Work for Hire)",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    text: "This project is designated as a 'Work made for hire.'",
                }),
                new Paragraph({ text: "- Upon receipt of the final 50% payment, the Developer will transfer 100% of the ownership, copyrights, and intellectual property rights of the custom-written source code to Micro Technique IT.", bullet: { level: 0 } }),
                new Paragraph({ text: "- The Client retains full rights to white-label, resell, modify, and distribute the software as they see fit.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({
                    text: "5. Data Privacy & Legal Compliance",
                    heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph({
                    text: "The platform involves the recording of telephone conversations and the extraction of personal user data (leads).",
                }),
                new Paragraph({ text: "- Legal Liability: Micro Technique IT assumes all legal responsibility for the operation of the SaaS platform.", bullet: { level: 0 } }),
                new Paragraph({ text: "- Compliance: It is the sole responsibility of the Client, and by extension their end-users, to ensure compliance with all applicable local, state, and federal telecom regulations (including Two-Party Consent recording laws) and data privacy regulations (such as GDPR or CCPA). The Developer assumes no liability for the misuse of the platform or failure to adhere to legal compliance by the Client or their users.", bullet: { level: 0 } }),
                new Paragraph({ text: "" }),
                new Paragraph({ text: "---" }),
                new Paragraph({ text: "" }),
                new Paragraph({ text: "Signatures:" }),
                new Paragraph({ text: "" }),
                new Paragraph({ text: "___________________________" }),
                new Paragraph({ children: [new TextRun({ text: "[Your Name] (Developer)", bold: true })] }),
                new Paragraph({ text: "Date: _______________" }),
                new Paragraph({ text: "" }),
                new Paragraph({ text: "___________________________" }),
                new Paragraph({ children: [new TextRun({ text: "Representative for Micro Technique IT", bold: true })] }),
                new Paragraph({ text: "Date: _______________" }),
            ],
        },
    ],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("SaaS_Development_Agreement.docx", buffer);
    console.log("Created SaaS_Development_Agreement.docx");
});
